# GitHub Action that keeps the PIM GitHub repo in sync with the git repo in Azure DevOps.
name: Update Azure DevOps Git Repo
on:
  push:
    branches:
      - '**'

jobs:
  sync_with_github_repo:
    name: Sync with GitHub repo
    runs-on: windows-latest
    steps:
      # Create a bare repo of the GitHub repo.
      - name: Clone GitHub Repo
        run: git clone --mirror https://github.com/Gabriel-Lemus/Product-Inventory-Manager.git

      # Change directory.
      - name: Change directory
        run: cd ./Product-Inventory-Manager.git/
      
      # Add a remote for the secondary repo in Azure DevOps.
      - name: Add Secondary Remote
        run: git remote add --mirror=fetch secondary https://3011591650101@dev.azure.com/3011591650101/Product%20Inventory%20Manager/_git/Product%20Inventory%20Manager

      # Get the commits and refs from the GitHub repo to the local repo.
      - name: Get Commits and References from the GitHub repo
        run: git fetch origin

      # Update Azure DevOps git repo
      - name: Update Azure DevOps repo with local refs
        run: git push secondary --all
