# GitHub Action that keeps the PIM GitHub repo in sync with the git repo in Azure DevOps.
name: Update Azure DevOps Git Repo
on:
  push:
    branches:
      - '**'

jobs:
  sync_with_github_repo:
    name: Sync with GitHub repo
    runs-on: ubuntu-latest
    steps:
      # Create a bare repo of the GitHub repo.
      - name: Clone GitHub Repo
        run: git clone --mirror https://github.com/Gabriel-Lemus/Product-Inventory-Manager.git

      # Change directory.
      - name: Change directory
        run: cd ./Product-Inventory-Manager.git/

      # Initialize auth agent.
      - name: Init auth agent
        run: ssh-agent /bin/sh

      # Add RSA key.
      - name: Add RSA key
        run: ssh-add "${{ secrets.SSH_KEY }}"

      # Add a remote for the secondary repo in Azure DevOps.
      # - name: Add Secondary Remote
      #   run: git remote add --mirror=fetch secondary git@ssh.dev.azure.com:v3/3011591650101/Product%20Inventory%20Manager/Product%20Inventory%20Manager

      # Get the commits and refs from the GitHub repo to the local repo.
      # - name: Get Commits and References from the GitHub repo
      #   run: git fetch origin

      # Update Azure DevOps git repo
      # - name: Update Azure DevOps repo with local refs
      #   run: git push secondary --all
